#script for twitter credentials constants
ACCESS_TOKEN = "YOUR API KEY"
ACCESS_TOKEN_SECRET = "YOUR API KEY"
CONSUMER_KEY = "YOUR API KEY"
CONSUMER_KEY_SECRET = "YOUR API KEY"
NEWS_API_KEY= "YOUR API KEY"
GOOGLE_API_KEY= "YOUR API KEY"
SEARCH_ID= "YOUR API KEY"